### ISSUE TITLE
Sugestions

### ISSUE THREAD

**Issue by soeshark** [Nader-Sl/Hackemon#112]
hello, its one great work you done until now.
I used just for some minutes to test, but i wold like to do some litle sugestions that can inprove the project.

1 - When the bot need to relogin while running, it jump to start position on the settings. Must save the current coordinates to use after relogin.
2 - Random intervals setting. E.g. in settings configure time in minutes the bot will run from x to y minutes and time of the stop from w to z minutos. While runing, bot will walk for randon interval between x and y, then stop for randon interval between w and z and resume for the next cicle.
3 - Fail catch is one great feature, but all the success catchs are perfect throws. Need rondomize between other throws too.
4 - The bot can already transfer and evolve, there is any option on the api to power up the pokemons too? The amout of stardust the account have is currently one of the itens that can couse the account to be flaged as bot. If possible wold be great to power up without have to login in the phone app or other emulator.
5 - Random walk speed, have on min and max speed in the settings and while walking, rondomize the speed between the values in the settings. No one in real life wald always the same speed.

**Comment by mkimid** [comment]
I want to add one more suggestion, 
For the walks simulation, there is one issue, 

Just image, there is a rectangular block and, two pokestop on middle-top and middle-bottom. 
                       A              A'
[=========|=========]
                       B              B'            C
when visit one side, it will move to bottom side around the way, if it takes longer than 5 minutes,
it will keep repeating the same locations between A and B, and 
It is ignoring A' B' C... whatever even it is going thru

to avoid this issues, I want to suggest two options

(1) Make possible to adjust the blocking time longer than 5 minutes
     - when moved from A to B, A will not be enabled, and then, it will going to B' instead A

(2) Decide the next stop using GOOGLE DISTANCE instead of GPS distance (point to point fly)
     - GPS distance : A-B is the most shortest way 
     - GOOGLE distance : A - A' is the most shortest way

**Comment by weslleyvreal** [comment]
so far all this pleases me , so not like the sniper be manual , since I am in pain in the fingers ... : D
