### ISSUE TITLE
The best configuration. Please share your experiences here!

### ISSUE THREAD

**Issue by PokemonAddict** [Nader-Sl/Hackemon#50]
I think it's time to work together and find out what's the best config out there. Please post like below!

Account config: Travel speed 175km/h 
Sniping: Yes. Sniping around 30 pokemons in one day. 
Ban: Yes. After around 2 days and then 6 hrs working bot. I guess first from softban to hardban now.

Solution? I think travel speed should be lover and work with VPN.

Thank you for sharing :-)

**Comment by PokemonAddict** [comment]
For further info: https://cloud.githubusercontent.com/assets/21040866/17669569/bb73c624-6340-11e6-9b14-d9d22bc62c2b.png

**Comment by Evertvaningen** [comment]
People are so stupid. 

Look at your speed... Traveling 175Km/h is the first problem. Travel 175Km/h all day is not normal.
NEVER SNIPE! This is GPS jumping which is BAD and BAN sensitive, just walk in a small area like 12Km/h

Slow = Safe
Fast = Stupid
Snipe = Retarded

GPS Jumping is the main cause along with too fast GPS speed which gets you banned.

**Comment by Evertvaningen** [comment]
HERE IS NEW INFO ON ALL BAN TYPES AND HOW TO POSSIBLY AVOID/BYPASS THEM 
(NOT 100% CONFIRMED) 

**Soft ban** 
Caused by jumping location. Unable to spin pokestops/catch pokemon/fight in gyms. Avoid it by either not jumping locations too quickly or by waiting before jumping there. A good estimate of how long you should wait is how long it would take to get there by flight. Can be bypassed by spinning a pokestop 1-50 times. 
**Capture ban** 
Caused by capturing more than 1000 pokemon in under 24 hours. Unable to capture pokemon. After ever hour, if your total pokemon in the last 24 hours is below the ban threshold, you'll be unbanned, If you surpass that threshold, you'll be banned again. Potential bypass by throwing missing pokeballs 15-30 times. 
**Pokestop ban** 
Caused by using more than 2000 pokestops in under 24 hours Unable to use pokestops. After ever hour, if your total pokestop uses in the last 24 hours is below the ban threshold, you'll be unbanned, If you surpass that threshold, you'll be banned again. No public way to bypass. 
**Temp IP ban** 
Caused by too many requests from the same IP. This ban prevents any MapObjects from being returned. (unable to find pokestops error) Will last anywhere from 10 minutes to a few hours depending on severity. Can be bypassed by using proxies. 
**Login Error ban** 
Possibly caused by login into multiple accounts with the same Deviceld. Potential bypass when you change Deviceld. Not much is known about this type of ban.

**Comment by Joannou1** [comment]
I've set my speed for 65Km/h, but it doesn't want to save and always stays at 100, though it doesn't look like 100.
Normal walk roads, fairly medium radius, I add 500-2000ms delay to capture and encounter actions to make it look naturalish. I only run the bot for 3-4 hours a day and have yet to snipe.

**Comment by FumaWeed** [comment]
**Using high speed, snipe but the same location, i 32 right now, no softban, no problems. My acc had two weeks botting. Cheers.**
